spring.application.name=demomvc
# Cấu hình kết nối MySQL
# Đổi 'crm_db' thành tên database bạn đã tạo trong MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_crm?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# Nhập mật khẩu MySQL của máy bạn vào đây
spring.datasource.password=123456

# Cấu hình Hibernate (JPA)
# 'update' sẽ tự động cập nhật schema nếu Entity thay đổi, nhưng không làm mất data cũ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect